### ISSUE TITLE
重复的CI job

### ISSUE THREAD

**Issue by blurrcat** [DaoCloud/daocloud-doc#1]
我在daocloud上连接了一个bitbucket的repo。在为当前branch创建pull request后，每次commit会触发两个CI job，
![image](https://cloud.githubusercontent.com/assets/2245575/7934067/c50dba86-0956-11e5-9447-be354b9a03d6.png)
其中第二个总是失败, console output:

``` bash
Step: git clone
+ git clone --recursive git@bitbucket.org:blurrcat/argus.git .
Cloning into '.'...
Warning: Permanently added 'bitbucket.org,131.103.20.168' (RSA) to the list of known hosts.
+ git fetch origin +refs/pull/bitbucket-update/head:refs/remotes/origin/pr/bitbucket-update
Warning: Permanently added the RSA host key for IP address '131.103.20.167' to the list of known hosts.
fatal: Couldn't find remote ref refs/pull/bitbucket-update/head
```

**Comment by sakeven** [comment]
这是因为pr会产生两个动作，push和 pr。而bitbucket不支持拿到pr代码，所以会失败。bitbucket pr的build之后我们会设置不在触发。

发自我的 Windows Phone

---

发件人: Harry Liangmailto:notifications@github.com
发送时间: ‎2015/‎6/‎2 18:42
收件人: DaoCloud/daocloud-docmailto:daocloud-doc@noreply.github.com
主题: [daocloud-doc] 重复的CI job (#1)

我在daocloud上连接了一个bitbucket的repo。在为当前branch创建pull request后，每次commit会触发两个CI job，
[image]https://cloud.githubusercontent.com/assets/2245575/7934067/c50dba86-0956-11e5-9447-be354b9a03d6.png
其中第二个总是失败, console output:

Step: git clone
- git clone --recursive git@bitbucket.org:blurrcat/argus.git .
  Cloning into '.'...
  Warning: Permanently added 'bitbucket.org,131.103.20.168' (RSA) to the list of known hosts.
- git fetch origin +refs/pull/bitbucket-update/head:refs/remotes/origin/pr/bitbucket-update
  Warning: Permanently added the RSA host key for IP address '131.103.20.167' to the list of known hosts.
  fatal: Couldn't find remote ref refs/pull/bitbucket-update/head

**Comment by blurrcat** [comment]
:+1:
